development:
  SENDGRID_USERNAME: brandnewbox
  SENDGRID_PASSWORD: GgJ3f)Tx
  SENDGRID_DOMAIN: anyfest.brandnewops.com

test:
  SENDGRID_USERNAME: brandnewbox
  SENDGRID_PASSWORD: GgJ3f)Tx
  SENDGRID_DOMAIN: anyfest.brandnewops.com

production:
  SENDGRID_USERNAME: brandnewbox
  SENDGRID_PASSWORD: GgJ3f)Tx
  SENDGRID_DOMAIN: anyfest.brandnewops.com
